export const USER_QUERY_KEY = "USER_QUERY_KEY";
export const EMPLOYEES_HR_KEY = "EMPLOYEES_HR_KEY";
export const LEAVE_REQUESTS_HR_KEY = "LEAVE_REQUESTS_HR_KEY";
export const APPROVAL_REQUESTS_HR_KEY = "APPROVAL_REQUESTS_HR_KEY";
export const APPROVAL_REQUESTS_EMPLOYEE_KEY = "APPROVAL_REQUESTS_EMPLOYEE_KEY";
export const READ_ONLY_PROJECTS_LIST_HR = "READ_ONLY_PROJECTS_LIST_HR";
export const READ_ONLY_PROJECTS_LIST_EMPLOYEE =
  "READ_ONLY_PROJECTS_LIST_EMPLOYEE";
