export const USER_QUERY_KEY = "USER_QUERY_KEY";
export const EMPLOYEES_HR_KEY = "EMPLOYEES_HR_KEY";
export const LEAVE_REQUESTS_HR_KEY = "LEAVE_REQUESTS_HR_KEY";
export const APPROVE_REQUESTS_HR_KEY = "APPROVE_REQUESTS_HR_KEY";
